### ISSUE TITLE
没有生成预期mock数据的问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [metersphere/jmeter-functions#1]
如下图，点击生成按钮为什么没有生成预期数据呢？对版本有什么要求吗？
![2021-11-11_154143](https://user-images.githubusercontent.com/41558924/141260447-0926beef-2cc5-4707-b2f9-45a566e4dae7.png)

**Comment by LuanShiZhiJian** [comment]
![image](https://user-images.githubusercontent.com/41558924/141261089-52533f2e-b2f8-471e-8941-60a09d9bbbe0.png)

报错供参考

**Comment by liuruibin** [comment]
<img width="1638" alt="image" src="https://github.com/metersphere/jmeter-functions/assets/23045261/64b05e7a-9906-45c4-8c2b-13ffcc721527">
请用最新版本试试


如果有使用问题请提issue到[主仓库](https://github.com/metersphere/metersphere/issues)，这里的issue可能不容易被看见
